#!/bin/bash
# source ./_env.sh
# source ../common/_function.sh

mkdir $INSTALLER_DIR
cd $INSTALLER_DIR

# # wget -O $FNAME_LIBSGX_DCAP_DEFAULT_QPL_DBG "$LIBSGX_DCAP_DEFAULT_QPL_DBG_URL"
wget -O $FNAME_LIBSGX_DCAP_DEFAULT_QPL_DEV "$LIBSGX_DCAP_DEFAULT_QPL_DEV_URL"
wget -O $FNAME_LIBSGX_DCAP_DEFAULT_QPL "$LIBSGX_DCAP_DEFAULT_QPL_URL"
wget -O $FNAME_LIBSGX_DCAP_PCCS "$LIBSGX_DCAP_PCCS_URL"
# # wget -O $FNAME_LIBSGX_DCAP_QL_DBG "$LIBSGX_DCAP_QL_DBG_URL"
wget -O $FNAME_LIBSGX_DCAP_QL_DEV "$LIBSGX_DCAP_QL_DEV_URL"
wget -O $FNAME_LIBSGX_DCAP_QL "$LIBSGX_DCAP_QL_URL"
# wget -O $FNAME_LIBSGX_ENCLAVE_COMMON_DBGSYM "$LIBSGX_ENCLAVE_COMMON_DBGSYM_URL"
wget -O $FNAME_LIBSGX_ENCLAVE_COMMON_DEV "$LIBSGX_ENCLAVE_COMMON_DEV_URL"
wget -O $FNAME_LIBSGX_ENCLAVE_COMMON "$LIBSGX_ENCLAVE_COMMON_URL"
wget -O $FNAME_SGX_LINUX_X64_DRIVER "$SGX_LINUX_X64_DRIVER_URL"
wget -O $FNAME_SGX_LINUX_X64_SDK "$SGX_LINUX_X64_SDK_URL"

chmod u+x $FNAME_SGX_LINUX_X64_DRIVER
chmod u+x $FNAME_SGX_LINUX_X64_SDK

__fn__notice "DONE"